
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "${PORTAINER_HTTPS_PORT:-9443}:9443"  # HTTPS UI
      - "${PORTAINER_HTTP_PORT:-9000}:9000"   # HTTP UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - traefik-network

volumes:
  portainer-data:
    name: portainer-data

networks:
  traefik-network:
    external: true
