# Traefik TLS certificates configuration (Let's Encrypt via certbot)
tls:
  certificates:
    - certFile: /letsencrypt/live/danilocatone.com/fullchain.pem
      keyFile: /letsencrypt/live/danilocatone.com/privkey.pem

  stores:
    default:
      defaultCertificate:
        certFile: /letsencrypt/live/danilocatone.com/fullchain.pem
        keyFile: /letsencrypt/live/danilocatone.com/privkey.pem
