http:
  middlewares:
    services:
      basicAuth:
        users:
          - 'dcatone:$$2a$$12$$Y2doS5wA6bupm2YJ.e1UuunCDRtLaPgPcte6pHLJl52SpQU7MzhGe' # bcrypt hash of your password
    compress:
      compress: {}
    hsts:
      headers:
        stsSeconds: 2592000
    redirect-to-portfolio:
      redirectRegex:
        regex: "^https?://([^/]+)/?$"
        replacement: "https://${1}/portfolio/"
        permanent: true
  routers:
    root-redirect:
      rule: "Path(`/`)"
      entrypoints:
        - websecure
      middlewares:
        - redirect-to-portfolio
      service: api@internal
      priority: 1
      tls: {}
    api:
      rule: Host(`traefik.danilocatone.com`)
      entrypoints:
        - websecure
      middlewares:
        - services
      service: api@internal

tls:
  certificates:
    - certFile: /letsencrypt/live/danilocatone.com/fullchain.pem
      keyFile: /letsencrypt/live/danilocatone.com/privkey.pem
  stores:
    default:
      defaultCertificate:
        certFile: /letsencrypt/live/danilocatone.com/fullchain.pem
        keyFile: /letsencrypt/live/danilocatone.com/privkey.pem
  options:
    default:
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
      sniStrict: true